apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-agent
  labels:
    k8s-app: {{ .Release.Name }}
    type: agent
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}
      type: agent
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name }}
        type: agent
        version: v1
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      initContainers:
      - name: wait-for-lapi
        image: "{{ .Values.agent.wait_for_lapi.image.repository }}:{{ .Values.agent.wait_for_lapi.image.tag }}"
        imagePullPolicy: {{ .Values.agent.wait_for_lapi.image.pullPolicy }}
        command: ['sh', '-c', "until nc {{ .Release.Name }}-service.{{ .Release.Namespace }} 8080; do echo waiting for lapi to start; sleep 5; done"]
      containers:
      - name: crowdsec-agent
        image: "{{ .Values.image.repository | default "crowdsecurity/crowdsec" }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: AGENT_USERNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: AGENT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: agent-credentials
                key: password
          - name: LOCAL_API_URL
            value: http://{{ .Release.Name }}-service.{{ .Release.Namespace }}:8080
          - name: DISABLE_LOCAL_API
            value: "true"
        {{- with .Values.agent.env }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.agent.resources | nindent 10 }}
        {{ if .Values.agent.metrics.enabled }}
        ports:
          - name: metrics
            containerPort: 6060
            protocol: TCP
        {{ end }}

        volumeMounts:
          - name: acquis-config-volume
            mountPath: /etc/crowdsec/acquis.yaml
            subPath: acquis.yaml
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: acquis-config-volume
        configMap:
          name: acquis-configmap
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
